package app

import (
	"orchestrator/internal/activities"
	"orchestrator/internal/workflows"

	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/worker"
)

func registerTemporalWorker(w worker.Worker, s *activities.Server) {
	w.RegisterWorkflow(workflows.RegisterAccountWorkflow)
	w.RegisterWorkflow(workflows.ActivateAccountWorkflow)
	w.RegisterWorkflow(workflows.AutoPayWorkflow)
	w.RegisterWorkflow(workflows.GoPayAppWorkflow)
	w.RegisterWorkflow(workflows.GoPayPaymentWorkflow)
	w.RegisterWorkflow(workflows.GoPayPaymentRebindWorkflow)
	w.RegisterWorkflow(workflows.ProbeAccountWorkflow)
	w.RegisterWorkflow(workflows.LoginSessionWorkflow)
	w.RegisterWorkflow(workflows.RegisterAndActivateWorkflow)
	w.RegisterWorkflow(workflows.RegisterMailboxWorkflow)
	w.RegisterWorkflow(workflows.MailboxOAuthWorkflow)

	w.RegisterActivityWithOptions(s.CreateJobActivity, activity.RegisterOptions{Name: createJobActivityName})
	w.RegisterActivityWithOptions(s.EnsureAccountActivity, activity.RegisterOptions{Name: ensureAccountActivityName})
	w.RegisterActivityWithOptions(s.ResolveAccountFromJobActivity, activity.RegisterOptions{Name: resolveAccountActivityName})
	w.RegisterActivityWithOptions(s.BrowserAuthStartActivity, activity.RegisterOptions{Name: browserAuthStartActivityName})
	w.RegisterActivityWithOptions(s.BrowserAuthCompleteActivity, activity.RegisterOptions{Name: browserAuthCompleteActivityName})
	w.RegisterActivityWithOptions(s.BrowserAuthCancelActivity, activity.RegisterOptions{Name: browserAuthCancelActivityName})
	w.RegisterActivityWithOptions(s.OTPWaitActivity, activity.RegisterOptions{Name: waitOTPActivityName})
	w.RegisterActivityWithOptions(s.FetchManualOTPActivity, activity.RegisterOptions{Name: fetchManualOTPActivityName})
	w.RegisterActivityWithOptions(s.EnsureLogonActivity, activity.RegisterOptions{Name: ensureLogonActivityName})
	w.RegisterActivityWithOptions(s.GoPayPaymentPrepareActivity, activity.RegisterOptions{Name: goPayPaymentPrepareActivityName})
	w.RegisterActivityWithOptions(s.GoPayPaymentStartActivity, activity.RegisterOptions{Name: goPayPaymentStartActivityName})
	w.RegisterActivityWithOptions(s.GoPayPaymentOTPResendActivity, activity.RegisterOptions{Name: goPayPaymentOTPResendActivityName})
	w.RegisterActivityWithOptions(s.GoPayPaymentCompleteActivity, activity.RegisterOptions{Name: goPayPaymentCompleteActivityName})
	w.RegisterActivityWithOptions(s.GoPayPaymentCancelActivity, activity.RegisterOptions{Name: goPayPaymentCancelActivityName})
	w.RegisterActivityWithOptions(s.GoPayResolveWAPhoneActivity, activity.RegisterOptions{Name: goPayResolveWAPhoneActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppLoadStateActivity, activity.RegisterOptions{Name: goPayAppLoadStateActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppSaveStateActivity, activity.RegisterOptions{Name: goPayAppSaveStateActivityName})
	w.RegisterActivityWithOptions(s.GoPayPaymentRebindSourceActivity, activity.RegisterOptions{Name: goPayPaymentRebindSourceActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppOTPStartActivity, activity.RegisterOptions{Name: goPayAppOTPStartActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppOTPCompleteActivity, activity.RegisterOptions{Name: goPayAppOTPCompleteActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppOTPRetryActivity, activity.RegisterOptions{Name: goPayAppOTPRetryActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppStatusActivity, activity.RegisterOptions{Name: goPayAppStatusActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppCreatePinStartActivity, activity.RegisterOptions{Name: goPayAppCreatePinStartActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppCreatePinRetryActivity, activity.RegisterOptions{Name: goPayAppCreatePinRetryActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppCreatePinCompleteActivity, activity.RegisterOptions{Name: goPayAppCreatePinCompleteActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppAcquireSignupPhoneActivity, activity.RegisterOptions{Name: goPayAppAcquireSignupPhoneActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppDiscardSignupPhoneActivity, activity.RegisterOptions{Name: goPayAppDiscardSignupPhoneActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppAddBalanceActivity, activity.RegisterOptions{Name: goPayAppAddBalanceActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppChangePhoneStartActivity, activity.RegisterOptions{Name: goPayAppChangePhoneStartActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppChangePhoneRetryActivity, activity.RegisterOptions{Name: goPayAppChangePhoneRetryActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppSMSCancelBeforeRotationActivity, activity.RegisterOptions{Name: goPayAppSMSCancelBeforeRotationActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppSMSFinishActivity, activity.RegisterOptions{Name: goPayAppSMSFinishActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppSMSRequestAdditionalCodeActivity, activity.RegisterOptions{Name: goPayAppSMSRequestAdditionalCodeActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppChangePhoneCompleteActivity, activity.RegisterOptions{Name: goPayAppChangePhoneCompleteActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppDeactivateStartActivity, activity.RegisterOptions{Name: goPayAppDeactivateStartActivityName})
	w.RegisterActivityWithOptions(s.GoPayAppDeactivateCompleteActivity, activity.RegisterOptions{Name: goPayAppDeactivateCompleteActivityName})
	w.RegisterActivityWithOptions(s.ProbePlusTrialAtomicActivity, activity.RegisterOptions{Name: probePlusTrialActivityName})
	w.RegisterActivityWithOptions(s.ProbeTierAtomicActivity, activity.RegisterOptions{Name: probeTierActivityName})
	w.RegisterActivityWithOptions(s.RegisterMailboxAtomicActivity, activity.RegisterOptions{Name: registerMailboxActivityName})
	w.RegisterActivityWithOptions(s.MailboxOAuthAtomicActivity, activity.RegisterOptions{Name: mailboxOAuthActivityName})
	w.RegisterActivityWithOptions(s.PersistRegisteredActivity, activity.RegisterOptions{Name: persistRegisteredActivityName})
	w.RegisterActivityWithOptions(s.PersistActivatedActivity, activity.RegisterOptions{Name: persistActivatedActivityName})
	w.RegisterActivityWithOptions(s.MarkJobFailedActivity, activity.RegisterOptions{Name: markJobFailedActivityName})
	w.RegisterActivityWithOptions(s.MarkJobSucceededActivity, activity.RegisterOptions{Name: markJobSucceededActivityName})
}
