package main

const (
	taskQueueDefault = "nb-register-orchestrator"

	createJobActivityName                       = "CreateJobActivity"
	ensureAccountActivityName                   = "EnsureAccountActivity"
	resolveAccountActivityName                  = "ResolveAccountFromJobActivity"
	browserAuthStartActivityName                = "BrowserAuthStartActivity"
	browserAuthCompleteActivityName             = "BrowserAuthCompleteActivity"
	browserAuthCancelActivityName               = "BrowserAuthCancelActivity"
	waitOTPActivityName                         = "OTPWaitActivity"
	fetchManualOTPActivityName                  = "FetchManualOTPActivity"
	ensureLogonActivityName                     = "EnsureLogonActivity"
	goPayPaymentStartActivityName               = "GoPayPaymentStartActivity"
	goPayPaymentCompleteActivityName            = "GoPayPaymentCompleteActivity"
	goPayPaymentCancelActivityName              = "GoPayPaymentCancelActivity"
	goPayAppOTPStartActivityName                = "GoPayAppOTPStartActivity"
	goPayAppOTPCompleteActivityName             = "GoPayAppOTPCompleteActivity"
	goPayAppChangePhoneStartActivityName        = "GoPayAppChangePhoneStartActivity"
	goPayAppChangePhoneRetryActivityName        = "GoPayAppChangePhoneRetryActivity"
	goPayAppSMSCancelBeforeRotationActivityName = "GoPayAppSMSCancelBeforeRotationActivity"
	goPayAppSMSFinishActivityName               = "GoPayAppSMSFinishActivity"
	goPayAppChangePhoneCompleteActivityName     = "GoPayAppChangePhoneCompleteActivity"
	goPayAppDeactivateStartActivityName         = "GoPayAppDeactivateStartActivity"
	goPayAppDeactivateCompleteActivityName      = "GoPayAppDeactivateCompleteActivity"
	probePlusTrialActivityName                  = "ProbePlusTrialAtomicActivity"
	probeTierActivityName                       = "ProbeTierAtomicActivity"
	registerMailboxActivityName                 = "RegisterMailboxAtomicActivity"
	mailboxOAuthActivityName                    = "MailboxOAuthAtomicActivity"
	persistRegisteredActivityName               = "PersistRegisteredActivity"
	persistActivatedActivityName                = "PersistActivatedActivity"
	markJobFailedActivityName                   = "MarkJobFailedActivity"
	markJobSucceededActivityName                = "MarkJobSucceededActivity"

	manualOTPSignalName = "manual_otp_available"
)
