apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nb-register.configName" . }}
  labels:
    {{- include "nb-register.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgres.auth.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  {{- range $key, $value := .Values.configEnv }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
