{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nb-register.appSecretName" . }}
  labels:
    {{- include "nb-register.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
  config.json: |-
    {{- .Values.gopayPaymentConfig.config | toPrettyJson | nindent 4 }}
{{- end }}
