// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: account_db.proto

/* eslint-disable */

export const protobufPackage = "accountdb";

export interface Account {
  account_id: string;
  email: string;
  password: string;
  status: string;
  error_message: string;
  session_token: string;
  charge_ref: string;
  first_name: string;
  last_name: string;
  /** YYYY-MM-DD */
  dob: string;
  created_at: number;
  updated_at: number;
  access_token: string;
  plus_trial_eligible?: boolean | undefined;
  plus_active?: boolean | undefined;
  tier: string;
  activation_channel?: string | undefined;
}

export interface CreateAccountRequest {
  account: Account | undefined;
}

export interface CreateAccountResponse {
  account: Account | undefined;
}

export interface GetAccountRequest {
  account_id: string;
}

export interface GetAccountResponse {
  account: Account | undefined;
}

export interface UpdateAccountRequest {
  account: Account | undefined;
}

export interface UpdateAccountResponse {
  account: Account | undefined;
}

export interface DeleteAccountRequest {
  account_id: string;
}

export interface DeleteAccountResponse {
  ack: boolean;
}

export interface ListAccountsRequest {
  status: string;
  limit: number;
  email: string;
}

export interface ListAccountsResponse {
  accounts: Account[];
}
