// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: gopay_app.proto

/* eslint-disable */

export const protobufPackage = "gopay_app";

export interface ChangePhoneStartRequest {
  pin: string;
  /** 编排服务从接码服务取号后传入，不含国家码 */
  new_phone: string;
  state_json: string;
}

export interface ChangePhoneStartResponse {
  success: boolean;
  error_message: string;
  /** 实际获取到的号码 */
  new_phone: string;
  /** 保留字段；activation_id 由编排服务传递给接码服务 */
  activation_id: string;
  otp_sent: boolean;
  state_json: string;
}

export interface ChangePhoneCompleteRequest {
  otp: string;
  state_json: string;
}

export interface ChangePhoneCompleteResponse {
  success: boolean;
  error_message: string;
  state_json: string;
}

export interface ChangePhoneRetryRequest {
  state_json: string;
}

export interface ChangePhoneRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  state_json: string;
}

export interface DeactivateStartRequest {
  pin: string;
  state_json: string;
}

export interface DeactivateStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  state_json: string;
}

export interface DeactivateCompleteRequest {
  otp: string;
  state_json: string;
}

export interface DeactivateCompleteResponse {
  success: boolean;
  error_message: string;
  deactivated_at: number;
  state_json: string;
}

export interface LoginStartRequest {
  /** 登录手机号；必填，由上游编排传入 */
  phone: string;
  /** 电话区号，例如 "+62"；必填，由上游编排传入 */
  country_code: string;
  /** 登录 PIN；必填，由上游编排传入 */
  pin: string;
  /** sms 或 wa；为空时使用服务默认配置 */
  otp_channel: string;
  state_json: string;
}

export interface LoginStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  state_json: string;
}

export interface LoginCompleteRequest {
  otp: string;
  state_json: string;
}

export interface LoginCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  state_json: string;
}

export interface SignupStartRequest {
  /** 新账号手机号；必填，由上游编排传入 */
  phone: string;
  name: string;
  email: string;
  /** 电话区号，例如 "+62"；默认 GOPAY_COUNTRY_CODE=62 */
  country_code: string;
  /** sms 或 wa；为空默认 sms；由服务映射为 otp_sms / otp_wa */
  otp_channel: string;
  state_json: string;
}

export interface SignupStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  /** 上游原始响应 JSON */
  raw_json: string;
  retry_timer_seconds: number[];
  state_json: string;
}

export interface SignupRetryRequest {
  state_json: string;
}

export interface SignupRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  /** 上游原始响应 JSON */
  raw_json: string;
  state_json: string;
}

export interface SignupCompleteRequest {
  otp: string;
  state_json: string;
}

export interface SignupCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_required: boolean;
  /** 上游原始响应 JSON */
  raw_json: string;
  state_json: string;
}

export interface CreatePinStartRequest {
  pin: string;
  /** sms 或 wa；为空默认 sms；由服务映射为 otp_sms / otp_wa */
  otp_channel: string;
  state_json: string;
}

export interface CreatePinStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  state_json: string;
}

export interface CreatePinRetryRequest {
  state_json: string;
}

export interface CreatePinRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  state_json: string;
}

export interface CreatePinCompleteRequest {
  otp: string;
  pin: string;
  state_json: string;
}

export interface CreatePinCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_complete: boolean;
  state_json: string;
}

export interface AuthStartRequest {
  /** 手机号；必填，由上游编排传入 */
  phone: string;
  /** 电话区号，例如 "+62"；默认 GOPAY_COUNTRY_CODE=62 */
  country_code: string;
  /** login 或 signup PIN setup 使用；为空时使用 GOPAY_PIN */
  pin: string;
  /** sms 或 wa；为空时使用服务默认配置 */
  otp_channel: string;
  state_json: string;
}

export interface AuthStartResponse {
  success: boolean;
  error_message: string;
  /** 自动判定结果：token、login 或 signup */
  mode: string;
  stage: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  ready: boolean;
  pin_setup_required: boolean;
  state_json: string;
}

export interface AuthCompleteRequest {
  otp: string;
  /** signup PIN setup 使用；为空时使用 GOPAY_PIN */
  pin: string;
  state_json: string;
}

export interface AuthCompleteResponse {
  success: boolean;
  error_message: string;
  /** 自动判定结果：token、login 或 signup */
  mode: string;
  stage: string;
  phone: string;
  ready: boolean;
  pin_setup_required: boolean;
  pin_setup_complete: boolean;
  state_json: string;
}

export interface CheckTokenValidRequest {
  state_json: string;
}

export interface CheckTokenValidResponse {
  success: boolean;
  error_message: string;
  stage: string;
  phone: string;
  token_valid: boolean;
  refreshed: boolean;
  balance_amount: number;
  has_min_balance: boolean;
  balance_currency: string;
  state_json: string;
}

export interface ClaimEnvelopeRequest {
  /** 为空时从 link 提取 */
  envelope_request_id: string;
  /** app.gopay 短链、gopay:// deeplink 或 customer API URL */
  link: string;
  state_json: string;
}

export interface ClaimEnvelopeResponse {
  success: boolean;
  error_message: string;
  /** 实际请求路径里的 id */
  envelope_request_id: string;
  /** 返回 data.envelope_request_id；可能与路径 id 不同 */
  response_envelope_request_id: string;
  status: string;
  http_status: number;
  raw_json: string;
  state_json: string;
}

export interface UnlinkRequest {
  state_json: string;
}

export interface UnlinkResponse {
  success: boolean;
  error_message: string;
  unlinked_count: number;
  state_json: string;
}

export interface StatusRequest {
  state_json: string;
}

export interface StatusResponse {
  stage: string;
  phone: string;
  /** 当前设备指纹摘要 */
  device_fingerprint: string;
  deactivated_at: number;
  error_message: string;
  token_present: boolean;
  login_otp_sent_at_unix: number;
  login_otp_expires_at_unix: number;
  signup_otp_sent_at_unix: number;
  signup_otp_expires_at_unix: number;
  signup_pin_otp_sent_at_unix: number;
  signup_pin_otp_expires_at_unix: number;
  balance_amount: number;
  has_min_balance: boolean;
  balance_currency: string;
  state_json: string;
}

export interface GetReadyAccountTokenRequest {
  state_json: string;
}

export interface GetReadyAccountTokenResponse {
  success: boolean;
  error_message: string;
  account_token: string;
  phone: string;
  state_json: string;
}

export interface CheckDeactivationRequest {
  state_json: string;
}

export interface CheckDeactivationResponse {
  completed: boolean;
  remaining_seconds: number;
  state_json: string;
}

export interface GetQrIdRequest {
  state_json: string;
}

export interface GetQrIdResponse {
  success: boolean;
  error_message: string;
  qr_id: string;
  state_json: string;
}

export interface CheckPhoneRequest {
  /** 不含国家码 */
  phone: string;
  /** 电话区号，例如 "+62"；默认 GOPAY_COUNTRY_CODE=62 */
  country_code: string;
}

export interface CheckPhoneResponse {
  /** true=未注册，可用于接收改号 */
  available: boolean;
  error_message: string;
  /** available / registered / rate_limited / error */
  status: string;
}

export interface ReplayStepResult {
  label: string;
  status_code: number;
  response_text: string;
  error_message: string;
}

export interface ReplayLinkPaymentRequest {
  /** Midtrans GoPay deeplink 或 A...ID payment reference */
  payment_link: string;
  pin: string;
  /** 默认 1 IDR */
  amount_value: number;
  amount_currency: string;
  body_limit: number;
  state_json: string;
}

export interface ReplayLinkPaymentResponse {
  success: boolean;
  error_message: string;
  payment_id: string;
  status: string;
  steps: ReplayStepResult[];
  state_json: string;
}

export interface GetGoPayStateRequest {
  /** local 或 tg:<user_id> */
  state_key: string;
}

export interface GetGoPayStateResponse {
  success: boolean;
  error_message: string;
  state_key: string;
  state_json: string;
}

export interface UpsertGoPayStateRequest {
  /** local 或 tg:<user_id> */
  state_key: string;
  state_json: string;
}

export interface UpsertGoPayStateResponse {
  success: boolean;
  error_message: string;
  state_key: string;
  state_json: string;
}

export interface DeleteGoPayStateRequest {
  /** local 或 tg:<user_id> */
  state_key: string;
}

export interface DeleteGoPayStateResponse {
  success: boolean;
  error_message: string;
}
