// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_gopay_app.proto

/* eslint-disable */
import type { StatusResponse } from "./gopay_app";

export const protobufPackage = "orchestrator";

export interface EnsureLogonRequest {
  job_id: string;
  account_id: string;
}

export interface EnsureLogonResponse {
  ready: boolean;
  stage: string;
  phone: string;
  status_before: StatusResponse | undefined;
  status_after: StatusResponse | undefined;
  already_ready: boolean;
  change_phone_complete: boolean;
  deactivate_complete: boolean;
  logon_complete: boolean;
  account_token_ready: boolean;
  error_message: string;
  signup_complete: boolean;
  signup_pin_complete: boolean;
}

export interface GoPayAppRequest {
}

export interface GoPayAppResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface GoPayPaymentRequest {
  account_id: string;
  source_job_id: string;
  /** sms 或 wa；默认 sms */
  otp_channel: string;
  /** 续跑已取号流程时复用同一个短信激活号 */
  sms_activation_id: string;
  add_balance: GoPayAddBalance | undefined;
  add_balance_confirm_timeout_seconds: number;
  /** local 或 tg:<user_id>；WA 接码来源和 GoPay state 归属用户 */
  user_id: string;
  /** WA 支付注册手机号；为空时使用 user_id 已保存值或本地配置 */
  wa_phone: string;
}

export interface GoPayPaymentResponse {
  job_id: string;
  started: boolean;
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
  activation_id: string;
  phone: string;
  add_balance_complete: boolean;
  add_balance_method: string;
  add_balance_status: string;
  wa_phone: string;
  bound_phone: string;
  change_phone_activation_id: string;
  change_phone_complete: boolean;
  user_id: string;
}

export interface GoPayPaymentRebindRequest {
  source_job_id: string;
  account_id: string;
  user_id: string;
}

export interface GoPayAddBalance {
  envelope?: GoPayEnvelopeAddBalance | undefined;
  manual_transfer?: GoPayManualTransferAddBalance | undefined;
  rekberinaja?: GoPayRekberinajaAddBalance | undefined;
}

export interface GoPayEnvelopeAddBalance {
  link: string;
  envelope_request_id: string;
}

export interface GoPayManualTransferAddBalance {
  instructions: string;
  amount: number;
  currency: string;
}

export interface GoPayRekberinajaAddBalance {
  endpoint_url: string;
  bearer_token: string;
  device_id: string;
  store: string;
  product_id: string;
  service_id: string;
  payment_method: string;
  invoice_email: string;
  promo_code: string;
  use_poin: boolean;
  user_agent: string;
  origin: string;
  referer: string;
  refresh_token: string;
  fee_total: number;
  poll_timeout_seconds: number;
  poll_interval_seconds: number;
}

export interface ManualAddBalanceSignal {
  kind: string;
  add_balance: GoPayAddBalance | undefined;
}

export interface ConfirmManualAddBalanceRequest {
  job_id: string;
  add_balance: GoPayAddBalance | undefined;
}

export interface ConfirmManualAddBalanceResponse {
  success: boolean;
  job_id: string;
  error_message: string;
}

export interface GoPayUserStatusRequest {
  user_id: string;
}

export interface GoPayUserStatusResponse {
  success: boolean;
  error_message: string;
  status: StatusResponse | undefined;
}

export interface GoPayUserClearStateRequest {
  user_id: string;
}

export interface GoPayUserClearStateResponse {
  success: boolean;
  error_message: string;
}

export interface GoPayUserSetWAPhoneRequest {
  user_id: string;
  wa_phone: string;
}

export interface GoPayUserGetWAPhoneRequest {
  user_id: string;
}

export interface GoPayUserWAPhoneResponse {
  success: boolean;
  error_message: string;
  user_id: string;
  wa_phone: string;
}

export interface GoPayUserAuthStartRequest {
  user_id: string;
  phone: string;
  country_code: string;
  pin: string;
  /** sms 或 wa；为空时使用服务默认配置 */
  otp_channel: string;
}

export interface GoPayUserAuthStartResponse {
  success: boolean;
  error_message: string;
  mode: string;
  stage: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
  ready: boolean;
  pin_setup_required: boolean;
}

export interface GoPayUserAuthCompleteRequest {
  user_id: string;
  otp: string;
  pin: string;
}

export interface GoPayUserAuthCompleteResponse {
  success: boolean;
  error_message: string;
  mode: string;
  stage: string;
  phone: string;
  ready: boolean;
  pin_setup_required: boolean;
  pin_setup_complete: boolean;
}

export interface GoPayUserChangePhoneStartRequest {
  user_id: string;
  new_phone: string;
  pin: string;
}

export interface GoPayUserChangePhoneStartResponse {
  success: boolean;
  error_message: string;
  new_phone: string;
  otp_sent: boolean;
}

export interface GoPayUserChangePhoneCompleteRequest {
  user_id: string;
  otp: string;
}

export interface GoPayUserChangePhoneCompleteResponse {
  success: boolean;
  error_message: string;
}

export interface GoPayUserChangePhoneRetryRequest {
  user_id: string;
}

export interface GoPayUserChangePhoneRetryResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
}

export interface GoPayUserSignupStartRequest {
  user_id: string;
  phone: string;
  name: string;
  email: string;
  country_code: string;
  /** sms 或 wa；为空默认 sms */
  otp_channel: string;
}

export interface GoPayUserSignupStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
}

export interface GoPayUserSignupCompleteRequest {
  user_id: string;
  otp: string;
}

export interface GoPayUserSignupCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_required: boolean;
}

export interface GoPayUserCreatePinStartRequest {
  user_id: string;
  pin: string;
  /** sms 或 wa；为空默认 sms */
  otp_channel: string;
}

export interface GoPayUserCreatePinStartResponse {
  success: boolean;
  error_message: string;
  otp_sent: boolean;
  verification_id: string;
  verification_method: string;
}

export interface GoPayUserCreatePinCompleteRequest {
  user_id: string;
  otp: string;
  pin: string;
}

export interface GoPayUserCreatePinCompleteResponse {
  success: boolean;
  error_message: string;
  phone: string;
  pin_setup_complete: boolean;
}

export interface GoPayAppWorkflowInput {
  job_id: string;
}

export interface GoPayAppWorkflowResult {
  job_id: string;
  success: boolean;
  error_message: string;
  activation_id: string;
  account_token_ready: boolean;
  change_phone_complete: boolean;
  deactivate_complete: boolean;
  signup_complete: boolean;
  signup_pin_complete: boolean;
}

export interface GoPayPaymentWorkflowInput {
  job_id: string;
  account_id: string;
  source_job_id: string;
  /** sms 或 wa；默认 sms */
  otp_channel: string;
  sms_activation_id: string;
  add_balance: GoPayAddBalance | undefined;
  add_balance_confirm_timeout_seconds: number;
  user_id: string;
  wa_phone: string;
}

export interface GoPayPaymentWorkflowResult {
  job_id: string;
  success: boolean;
  error_message: string;
  activation_id: string;
  phone: string;
  account_token_ready: boolean;
  signup_complete: boolean;
  signup_pin_complete: boolean;
  charge_ref: string;
  snap_token: string;
  add_balance_complete: boolean;
  add_balance_method: string;
  add_balance_status: string;
  wa_phone: string;
  bound_phone: string;
  change_phone_activation_id: string;
  change_phone_complete: boolean;
  user_id: string;
}

export interface GoPayPaymentRebindWorkflowInput {
  job_id: string;
  source_job_id: string;
  account_id: string;
  user_id: string;
}

export interface GoPayPaymentRebindWorkflowResult {
  job_id: string;
  success: boolean;
  error_message: string;
  source_job_id: string;
  account_id: string;
  activation_id: string;
  bound_phone: string;
  change_phone_complete: boolean;
  user_id: string;
  wa_phone: string;
}

export interface GoPayAppStepInput {
  job_id: string;
  activation_id: string;
  state_json: string;
}

export interface GoPayAppStepOutput {
  activation_id: string;
  ready: boolean;
  stage: string;
  phone: string;
  account_token_ready: boolean;
  change_phone_complete: boolean;
  deactivate_complete: boolean;
  signup_complete: boolean;
  signup_pin_complete: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppChangePhoneStartInput {
  job_id: string;
  failure_count: number;
  state_json: string;
  activation_id: string;
  phone: string;
}

export interface GoPayAppChangePhoneStartOutput {
  activation_id: string;
  phone: string;
  failure_count: number;
  max_failures: number;
  otp_timeout_seconds: number;
  otp_retry_attempts: number;
  data: { [key: string]: any } | undefined;
  state_json: string;
  retryable_failure: boolean;
  error_message: string;
}

export interface GoPayAppChangePhoneGetNumberInput {
  job_id: string;
  failure_count: number;
}

export interface GoPayAppChangePhoneGetNumberOutput {
  activation_id: string;
  phone: string;
  failure_count: number;
  max_failures: number;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppAcquireSignupPhoneInput {
  job_id: string;
  failure_count: number;
}

export interface GoPayAppAcquireSignupPhoneOutput {
  activation_id: string;
  phone: string;
  failure_count: number;
  max_failures: number;
  otp_timeout_seconds: number;
  data: { [key: string]: any } | undefined;
}

export interface GoPayResolveWAPhoneInput {
  job_id: string;
  user_id: string;
  wa_phone: string;
}

export interface GoPayResolveWAPhoneOutput {
  user_id: string;
  wa_phone: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppStateActivityInput {
  job_id: string;
  user_id: string;
  state_json: string;
  reason: string;
}

export interface GoPayAppStateActivityOutput {
  user_id: string;
  state_json: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayPaymentRebindSourceInput {
  job_id: string;
  source_job_id: string;
  account_id: string;
  user_id: string;
}

export interface GoPayPaymentRebindSourceOutput {
  source_job_id: string;
  account_id: string;
  user_id: string;
  wa_phone: string;
  charge_ref: string;
  snap_token: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppAddBalanceInput {
  job_id: string;
  state_json: string;
  add_balance: GoPayAddBalance | undefined;
  target_phone: string;
}

export interface GoPayAppAddBalanceOutput {
  success: boolean;
  error_message: string;
  method: string;
  status: string;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppChangePhoneRetryInput {
  job_id: string;
  activation_id: string;
  otp_attempt: number;
  state_json: string;
}

export interface GoPayAppChangePhoneRetryOutput {
  activation_id: string;
  otp_sent: boolean;
  error_message: string;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppSMSActivationInput {
  job_id: string;
  activation_id: string;
  failure_count: number;
  reason: string;
}

export interface GoPayAppSMSActivationOutput {
  activation_id: string;
  failure_count: number;
  max_failures: number;
  error_message: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppChangePhoneCompleteInput {
  job_id: string;
  activation_id: string;
  code: string;
  failure_count: number;
  state_json: string;
}

export interface GoPayAppChangePhoneCompleteOutput {
  activation_id: string;
  change_phone_complete: boolean;
  retryable_failure: boolean;
  failure_count: number;
  max_failures: number;
  error_message: string;
  stage: string;
  phone: string;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppDeactivateStartInput {
  job_id: string;
  activation_id: string;
  state_json: string;
}

export interface GoPayAppDeactivateStartOutput {
  activation_id: string;
  otp_required: boolean;
  timeout_seconds: number;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppDeactivateCompleteInput {
  job_id: string;
  activation_id: string;
  code: string;
  state_json: string;
}

export interface GoPayAppDeactivateCompleteOutput {
  activation_id: string;
  deactivate_complete: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayAppOTPStartInput {
  job_id: string;
  operation: string;
  step_name: string;
  phone: string;
  /** sms 或 wa；默认 sms */
  otp_channel: string;
  sms_activation_id: string;
  reset_state: boolean;
  state_json: string;
}

export interface GoPayAppCreatePinStartInput {
  job_id: string;
  /** sms 或 wa；默认 sms */
  otp_channel: string;
  sms_activation_id: string;
  state_json: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayAppOTPOutput {
  operation: string;
  otp_required: boolean;
  issued_after_unix: number;
  timeout_seconds: number;
  ready: boolean;
  account_token_ready: boolean;
  signup_complete: boolean;
  signup_pin_complete: boolean;
  pin_setup_required: boolean;
  stage: string;
  phone: string;
  data: { [key: string]: any } | undefined;
  verification_method: string;
  otp_channel: string;
  state_json: string;
}

export interface GoPayAppCreatePinCompleteInput {
  job_id: string;
  otp_param: string;
  submitted_at_param: string;
  issued_after_unix: number;
  otp_source: string;
  data: { [key: string]: any } | undefined;
  otp_channel: string;
  sms_activation_id: string;
  state_json: string;
}

export interface GoPayAppOTPCompleteInput {
  job_id: string;
  operation: string;
  otp_param: string;
  submitted_at_param: string;
  issued_after_unix: number;
  otp_source: string;
  data: { [key: string]: any } | undefined;
  otp_channel: string;
  sms_activation_id: string;
  state_json: string;
}
