// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_otp.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export interface OTPWaitInput {
  job_id: string;
  step_name: string;
  email?: OTPWaitEmailTarget | undefined;
  payment?: OTPWaitPaymentTarget | undefined;
  sms?: OTPWaitSMSTarget | undefined;
  timeout_seconds: number;
  issued_after_unix: number;
  otp_param: string;
  submitted_at_param: string;
}

export interface OTPWaitEmailTarget {
  email: string;
}

export interface OTPWaitPaymentTarget {
  source: string;
  purpose: string;
}

export interface OTPWaitSMSTarget {
  activation_id: string;
}

export interface OTPWaitOutput {
  found: boolean;
  source: string;
  code: string;
  error_message: string;
  data: { [key: string]: any } | undefined;
  activation_id: string;
}

export interface ManualOTPSignal {
  kind: string;
}

export interface SubmitOTPRequest {
  job_id: string;
  account_id: string;
  otp: string;
}

export interface SubmitOTPResponse {
  success: boolean;
  job_id: string;
  error_message: string;
}
