// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_job.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export interface CreateJobInput {
  job_id: string;
  account_id: string;
  action: string;
  params: { [key: string]: string };
}

export interface CreateJobInput_ParamsEntry {
  key: string;
  value: string;
}

export interface ResolveAccountInput {
  account_id: string;
  source_job_id: string;
}

export interface JobFailureInput {
  job_id: string;
  step_name: string;
  status: string;
  recoverable: boolean;
  retryable: boolean;
  error_message: string;
  result: { [key: string]: any } | undefined;
}

export interface JobSuccessInput {
  job_id: string;
  result: { [key: string]: any } | undefined;
}

export interface JobStep {
  step_name: string;
  status: string;
  recoverable: boolean;
  retryable: boolean;
  error_message: string;
  detail: { [key: string]: any } | undefined;
  started_at: number;
  completed_at: number;
}

export interface Job {
  job_id: string;
  account_id: string;
  action: string;
  status: string;
  recoverable: boolean;
  retryable: boolean;
  last_step: string;
  error_message: string;
  result: { [key: string]: any } | undefined;
  created_at: number;
  updated_at: number;
  steps: JobStep[];
}

export interface WorkflowProgress {
  job_id: string;
  workflow: string;
  step_name: string;
  status: string;
  error_message: string;
  updated_at_unix: number;
}

export interface JobSnapshot {
  job: Job | undefined;
  progress: WorkflowProgress | undefined;
  event_id: number;
}

export interface JobEvent {
  event_id: number;
  job_id: string;
  event_type: string;
  snapshot: JobSnapshot | undefined;
}

export interface GetJobRequest {
  job_id: string;
}

export interface GetJobResponse {
  snapshot: JobSnapshot | undefined;
  error_message: string;
}

export interface ListJobsRequest {
  limit: number;
  status: string;
  action: string;
  account_id: string;
}

export interface ListJobsResponse {
  snapshots: JobSnapshot[];
  error_message: string;
}

export interface WatchJobRequest {
  job_id: string;
  after_event_id: number;
}

export interface WatchJobResponse {
  event: JobEvent | undefined;
  error_message: string;
}

export interface WatchJobsRequest {
  job_ids: string[];
  status: string;
  after_event_id: number;
}

export interface WatchJobsResponse {
  event: JobEvent | undefined;
  error_message: string;
}
