// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: orchestrator_payment.proto

/* eslint-disable */

export const protobufPackage = "orchestrator";

export interface PersistActivatedInput {
  account_id: string;
  session_token: string;
  access_token: string;
  charge_ref: string;
  plus_trial_eligible: boolean;
  plus_trial_checked: boolean;
  plus_active: boolean;
}

export interface ProbePlusTrialActivityInput {
  job_id: string;
  account_id: string;
}

export interface ProbeTierActivityInput {
  job_id: string;
  account_id: string;
}

export interface ProbePlusTrialActivityOutput {
  success: boolean;
  checked: boolean;
  plus_trial_eligible: boolean;
  plus_active: boolean;
  amount: number;
  currency: string;
  source: string;
  plan_type: string;
  checkout_url: string;
  checkout_session_id: string;
  error_message: string;
  data: { [key: string]: any } | undefined;
}

export interface ProbeTierActivityOutput {
  success: boolean;
  checked: boolean;
  tier: string;
  plus_active: boolean;
  source: string;
  error_message: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayActivityInput {
  job_id: string;
  account_id: string;
  session_token: string;
  access_token: string;
  use_account_token: boolean;
  tokenization: string;
  checkout_url: string;
  checkout_session_id: string;
  /** sms 时 payment 触发 resend-otp；wa/空值不触发 */
  otp_channel: string;
  state_json: string;
  prepared_flow_id: string;
  gopay_phone: string;
  sms_activation_id: string;
  /** WA 接码来源；local 或 tg:<user_id> */
  state_key: string;
}

export interface GoPayActivityOutput {
  charge_ref: string;
  snap_token: string;
  plus_trial_eligible: boolean;
  plus_trial_checked: boolean;
  plus_active: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayPaymentStartOutput {
  flow_id: string;
  issued_after_unix: number;
  otp_timeout_seconds: number;
  use_account_token: boolean;
  data: { [key: string]: any } | undefined;
  otp_required: boolean;
  state_json: string;
}

export interface GoPayPaymentPrepareOutput {
  flow_id: string;
  snap_token: string;
  checkout_url: string;
  checkout_session_id: string;
  use_account_token: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayPaymentCompleteInput {
  job_id: string;
  account_id: string;
  flow_id: string;
  otp_param: string;
  submitted_at_param: string;
  otp_issued_after_unix: number;
  otp_source: string;
  use_account_token: boolean;
  data: { [key: string]: any } | undefined;
  state_json: string;
}

export interface GoPayPaymentOTPResendInput {
  job_id: string;
  account_id: string;
  flow_id: string;
  data: { [key: string]: any } | undefined;
}

export interface GoPayPaymentOTPResendOutput {
  success: boolean;
  flow_id: string;
  issued_after_unix: number;
  data: { [key: string]: any } | undefined;
}

export interface GoPayPaymentCancelInput {
  flow_id: string;
}

export interface ActivateAccountRequest {
  job_id: string;
  account_id: string;
}

export interface ActivateAccountResponse {
  job_id: string;
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
}

export interface ProbeAccountRequest {
  account_id: string;
}

export interface ProbeAccountResponse {
  job_id: string;
  started: boolean;
  error_message: string;
}

export interface ActivateAccountWorkflowInput {
  job_id: string;
  account_id: string;
  source_job_id: string;
  action: string;
}

export interface ActivateAccountWorkflowResult {
  job_id: string;
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
}

export interface AutoPayWorkflowInput {
  job_id: string;
  account_id: string;
  source_job_id: string;
}

export interface AutoPayWorkflowResult {
  job_id: string;
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
}

export interface ProbeAccountWorkflowInput {
  job_id: string;
  account_id: string;
}

export interface ProbeAccountWorkflowResult {
  job_id: string;
  success: boolean;
  plus_trial_checked: boolean;
  plus_trial_eligible: boolean;
  tier_checked: boolean;
  tier: string;
  plus_active: boolean;
  amount: number;
  currency: string;
  source: string;
  plan_type: string;
  checkout_url: string;
  error_message: string;
}
