// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: payment.proto

/* eslint-disable */

export const protobufPackage = "payment";

export interface StartGoPayRequest {
  session_token: string;
  access_token: string;
  use_account_token: boolean;
  tokenization: string;
  checkout_url: string;
  checkout_session_id: string;
  gopay_phone: string;
  /** sms 时调用 resend-otp；wa/空值只走 user-consent */
  otp_channel: string;
}

export interface PrepareGoPayRequest {
  session_token: string;
  access_token: string;
  tokenization: string;
  checkout_url: string;
  checkout_session_id: string;
  gopay_phone: string;
}

export interface PrepareGoPayResponse {
  success: boolean;
  error_message: string;
  flow_id: string;
  snap_token: string;
  checkout_url: string;
  checkout_session_id: string;
}

export interface StartPreparedGoPayRequest {
  flow_id: string;
  gopay_phone: string;
  /** sms 时调用 resend-otp；wa/空值只走 user-consent */
  otp_channel: string;
}

export interface StartGoPayResponse {
  success: boolean;
  error_message: string;
  flow_id: string;
  snap_token: string;
  issued_after_unix: number;
  expires_at_unix: number;
  checkout_url: string;
  checkout_session_id: string;
  otp_required: boolean;
}

export interface ProbePlusTrialPaymentRequest {
  session_token: string;
  access_token: string;
}

export interface ProbePlusTrialPaymentResponse {
  success: boolean;
  error_message: string;
  checked: boolean;
  plus_trial_eligible: boolean;
  amount: number;
  currency: string;
  source: string;
  checkout_url: string;
  plus_active: boolean;
  plan_type: string;
  checkout_session_id: string;
}

export interface CreateCheckoutLinkRequest {
  session_token: string;
  access_token: string;
}

export interface CreateCheckoutLinkResponse {
  success: boolean;
  error_message: string;
  checkout_url: string;
  checkout_session_id: string;
}

export interface ProbeTierPaymentRequest {
  session_token: string;
}

export interface ProbeTierPaymentResponse {
  success: boolean;
  error_message: string;
  checked: boolean;
  tier: string;
  plus_active: boolean;
  source: string;
}

export interface CompleteGoPayRequest {
  flow_id: string;
  otp: string;
}

export interface ResendGoPayOTPRequest {
  flow_id: string;
}

export interface ResendGoPayOTPResponse {
  success: boolean;
  error_message: string;
  flow_id: string;
  issued_after_unix: number;
}

export interface ConfirmGoPayPaymentRequest {
  flow_id: string;
}

export interface CancelGoPayRequest {
  flow_id: string;
}

export interface CancelGoPayResponse {
  success: boolean;
  error_message: string;
}

export interface GoPayResponse {
  success: boolean;
  error_message: string;
  charge_ref: string;
  snap_token: string;
  awaiting_manual_confirmation: boolean;
  deeplink_url: string;
  qr_code_url: string;
  finish_redirect_url: string;
  finish_200_redirect_url: string;
}
